
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-deployment
  labels:
    app: game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
      - name: game
        image: ${IMAGE}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 1048Mi
          requests:
            cpu: 100m
            memory: 256Mi        
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: game-service
spec:
  selector:
    app: game
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
